name: frontend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  animate_do: ^3.3.4
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  flutter_otp_text_field: ^1.1.3+2
  flutter_secure_storage: ^9.2.2
  mailer: ^6.1.2
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.0
  socket_io_client: ^2.0.3+1
  accordion: ^2.6.0
  image_picker: ^1.1.2
  mime: ^1.0.6
  fl_chart: ^0.69.0
  syncfusion_flutter_calendar: ^27.1.48
  google_nav_bar: ^5.0.6
  url_launcher: ^6.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/l10n/
    - assets/lang/